title: Pat Williams # your name (or website title) here
logo: "/images/headShot.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Lehigh University 
  <br>
  BS in Economics 23'
  <br>
  BA in Physics 23'
  <br>
  MS in Business Analytics 24'
  <br><br>
  <a href="https://www.linkedin.com/in/patrick-williams0/">LinkedIn</a> 
  <br>
  <a href="https://github.com/patwilliams04/patwilliams.github.io/blob/master/images/Pat_Williams_2024_CV.pdf">Resume</a>  
  <br>
  <a href="https://github.com/patwilliams04/FinDSCIAssignments2024" class="btn btn--info">Portfolio</a>  
  <br>
  <a href="https://github.com/patwilliams04">GitHub</a> 
  
theme: jekyll-theme-minimal
